name: Convert Videos to HLS

on:
  push:
    paths:
      - "*.mp4"
      - "*.mkv"
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Convert videos to HLS
        run: |
          mkdir -p public
          for file in *.mp4 *.mkv; do
            [ -e "$file" ] || continue
            name=$(basename "$file" | sed 's/\.[^.]*$//')
            mkdir -p "public/$name"
            echo "Converting $file -> public/$name/playlist.m3u8"
            ffmpeg -i "$file" \
              -c:v libx264 -c:a aac \
              -hls_time 10 -hls_list_size 0 -f hls \
              "public/$name/playlist.m3u8"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
